name: Build and deploy Next.js app to Azure Web App - NVS-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app (skip ESLint)
        run: NEXT_DISABLE_ESLINT_PLUGIN=true npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: |
            .next
            public
            package.json
            package-lock.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "NVS-web"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_725A5409556D4BD89159C5FA8A504221 }}
